# Site settings
image_location: assets/img
javascript_location: assets/js
url: "http://www.gsetri.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/_sass
  style: :compressed